# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jepsteindocker/docker-react -f Dockerfile.dev .

script:
  # - docker run jepsteindocker/docker-react npm run test -- --coverage
  - docker run -e CI=true jepsteindocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-711629017260"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"